@echo off
REM Clearing the “Recent Items” folder...
echo Clearing the "Recent Items" folder...
del /q "%AppData%\Microsoft\Windows\Recent\*" 2>nul

REM Deleting Quick Access data...
echo Deleting Quick Access data...
del /f /q "%AppData%\Microsoft\Windows\Recent\AutomaticDestinations\*" 2>nul

REM Restarting Explorer to apply changes...
echo Restarting Explorer to apply changes...
taskkill /f /im explorer.exe >nul 2>&1
start explorer.exe

REM Operation completed...
echo Operation completed. Quick Access recent items have been cleared.
pause


